### PR TITLE
Fix broken kdump addon on Rawhide

### PR DESCRIPTION
**Pull request by jkonecny12**
Thanks to the recent changes in Anaconda the Kdump addon needs to migrate with Anaconda changes.

* Fix imports after Anaconda refactoring.
* Use Simpleline library instead of old Anaconda solution.
* Minor things in the code.

The new Simpleline structure is quite different if you want to know more you can look on [documentation](https://python-simpleline.readthedocs.io/en/latest/).

### CODE REVIEW

**Comment by daveyoung** [comment]
Hi,  thanks for the fix, do you know how to do a test with rawhide changes of anaconda?

**Comment by jkonecny12** [comment]
I fear that there is not an easy way. I think the best approach is to build the RPM file for this addon and then use [makeupdates](https://github.com/rhinstaller/anaconda/blob/master/scripts/makeupdates) script from Anaconda code base like this:
```
makeupdates -a <path_to_rpm>
```
Then you should see `updates.img` file in root directory which can be uploaded to a visible server and used on kernel command line like 
```
inst.updates=http://<server>/path/updates.img inst.kdump_addon
```
That `inst.kdump_addon` is required for Fedora but I guess you know that.

Or you can use [this tutoriaI](http://rhinstaller.github.io/anaconda-addon-development-guide/sect-anaconda-addon-deploying-testing.html) or you can try my small project for creating updates images https://github.com/jkonecny12/anaconda_updates.

I also encourage you to look on text UI, thanks to the migration to Simpleline it could be slightly different.

**Comment by daveyoung** [comment]
Hmm, I think I know how to test the addon as an updates.img, but I'm afraid I do not know how to get latest ananconda rawhide code in an boot.iso, I guess this change needs the latest anaconda..

**Comment by jkonecny12** [comment]
Ohh I misunderstood then, sorry. This change needs current Anaconda from Rawhide. The kdump addon is broken on Rawhide Anaconda right now.

You can use this newest rawhide image http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/iso/ .

Boot iso above should be enough but if you want to try even Anaconda which is not released yet then use makeupdates script from the master branch of Anaconda with `-t` param like this
```
./scripts/makeupdates -t anaconda-28.18-1 -a <path_to_rpm>
```
That will create updates.img with all the changes which are not in `anaconda-28.18` (latest rawhide Anaconda now).

**Comment by daveyoung** [comment]
Hi,  it looks good when I select/deselect the options in tui, but I can not verify the actual result after installation finished, seems "Installation source" setting hangs..

**Pull request merged**
