### PR TITLE
Use kernel_arguments instead of cmdline

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Change all usages of `pyanaconda.flags.cmdline` to `pyanaconda.kernel.kernel_arguments` according to recent changes in pyanaconda 32.18 (already released).

### CODE REVIEW

**Comment by ryncsn** [comment]
Hi, thanks for the PR, should I backport this to F31?

**Comment by VladimirSlavik** [comment]
Hi @ryncsn! Sorry, that was not so clearly worded. The changes in Anaconda will be only in F32 (now rawhide).

**Comment by ryncsn** [comment]
It looks good to me, will release a new rawhide build, thanks!

**Comment by VladimirSlavik** [comment]
Thank you!

**Comment by VladimirSlavik** [comment]
Hello @ryncsn , can I help with the update somehow? Or did I miss it? I don't see anything in Bodhi...
https://bodhi.fedoraproject.org/updates/?packages=kdump-anaconda-addon

**Comment by ryncsn** [comment]
Hi @VladimirSlavik, just released a new build, sorry for the delay.

**Comment by VladimirSlavik** [comment]
@ryncsn thank you, and sorry too - I realized later that it's a holiday season for you.

**Pull request merged**
